# Generated by Django 6.0.2 on 2026-03-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=20, unique=True, verbose_name='USN / Roll Number')),
                ('department', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
