# Generated by Django 6.0.2 on 2026-03-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherallotment',
            unique_together=set(),
        ),
    ]
