# Generated by Django 6.0.2 on 2026-03-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='semester',
        ),
    ]
