# Generated by Django 6.0.2 on 2026-03-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=True)),
                ('subject', models.CharField(blank=True, help_text='Subject they teach (used to prevent invigilating their own subject)', max_length=100, null=True)),
                ('workload', models.IntegerField(default=0)),
            ],
        ),
    ]
