# Generated by Django 6.0.2 on 2026-03-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
