# Generated by Django 6.0.2 on 2026-03-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teacher_availability_remove_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='faculty_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Faculty ID'),
        ),
    ]
